name: Basicis | CI - Dev
on: 
  push: 
    branchs: 
     - dev
  pull_request:
    branchs: 
      - dev
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Composer ğŸ”§
        uses: php-actions/composer@v1

      - name: PHPUnit Tests âœ…
        run: |
          bash $GITHUB_WORKSPACE/.github/scripts/test.sh